//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pinit.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardFollow
    {
        public int StreamId { get; set; }
        public int BoardId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual FollowStream FollowStream { get; set; }
    }
}
