//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pinit.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Board
    {
        public Board()
        {
            this.BoardFollows = new HashSet<BoardFollow>();
            this.Pins = new HashSet<Pin>();
        }
    
        public int BoardId { get; set; }
        public string BoardName { get; set; }
        public string BoardOwner { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool PrivateComments { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<BoardFollow> BoardFollows { get; set; }
        public virtual ICollection<Pin> Pins { get; set; }
    }
}
