//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pinit.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public Picture()
        {
            this.Pins = new HashSet<Pin>();
        }
    
        public int PictureId { get; set; }
        public string ImageUrl { get; set; }
        public System.DateTime DateUploaded { get; set; }
    
        public virtual ICollection<Pin> Pins { get; set; }
    }
}
