//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pinit.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pin
    {
        public Pin()
        {
            this.Comments = new HashSet<Comment>();
            this.PinTags = new HashSet<PinTag>();
            this.UserLikes = new HashSet<UserLike>();
            this.Pin1 = new HashSet<Pin>();
            this.Pins = new HashSet<Pin>();
        }
    
        public int PinId { get; set; }
        public int PictureId { get; set; }
        public int BoardId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual ICollection<PinTag> PinTags { get; set; }
        public virtual ICollection<UserLike> UserLikes { get; set; }
        public virtual ICollection<Pin> Pin1 { get; set; }
        public virtual ICollection<Pin> Pins { get; set; }
    }
}
