//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pinit.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Boards = new HashSet<Board>();
            this.Comments = new HashSet<Comment>();
            this.FollowStreams = new HashSet<FollowStream>();
            this.Friends = new HashSet<Friend>();
            this.Friends1 = new HashSet<Friend>();
            this.UserLikes = new HashSet<UserLike>();
        }
    
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime DateRegistered { get; set; }
    
        public virtual ICollection<Board> Boards { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<FollowStream> FollowStreams { get; set; }
        public virtual ICollection<Friend> Friends { get; set; }
        public virtual ICollection<Friend> Friends1 { get; set; }
        public virtual ICollection<UserLike> UserLikes { get; set; }
    }
}
